INCOMPLETE lang/sbcl: update to sbcl-2.2.6
- [ x ] Patched inclusion of zstd with compression which is now part

- [   ] make-target-1.sh failing:

               fi ; \
               : ) > sbcl.mk
     /bin/sh: etags: command not found
     /usr/bin/clang -g -Wall -fdollars-in-identifiers -fno-omit-frame-pointer -I/opt/local/include -I../src/runtime   grovel-headers.c  -lSystem -lc -ldl -lpthread -L/opt/local/lib -lzstd -o grovel-headers
     grovel-headers.c:402:29: error: use of undeclared identifier 'page_index_t'
         DEFTYPE("page-index-t", page_index_t);
                                 ^
     grovel-headers.c:402:5: error: use of undeclared identifier 'foo'; did you mean 'for'?
         DEFTYPE("page-index-t", page_index_t);
         ^
     grovel-headers.c:78:15: note: expanded from macro 'DEFTYPE'
                (((foo=-1)<0) ? "signed" : "unsigned"), (8LU * (sizeof foo))); }
                   ^
     grovel-headers.c:402:5: error: expected expression
     grovel-headers.c:78:15: note: expanded from macro 'DEFTYPE'
                (((foo=-1)<0) ? "signed" : "unsigned"), (8LU * (sizeof foo))); }
                   ^
     grovel-headers.c:402:5: error: use of undeclared identifier 'foo'
     grovel-headers.c:78:67: note: expanded from macro 'DEFTYPE'
                (((foo=-1)<0) ? "signed" : "unsigned"), (8LU * (sizeof foo))); }
                                                                       ^
     grovel-headers.c:403:35: error: use of undeclared identifier 'generation_index_t'
         DEFTYPE("generation-index-t", generation_index_t);
                                       ^
     grovel-headers.c:403:5: error: use of undeclared identifier 'foo'; did you mean 'for'?
         DEFTYPE("generation-index-t", generation_index_t);
         ^
     grovel-headers.c:78:15: note: expanded from macro 'DEFTYPE'
                (((foo=-1)<0) ? "signed" : "unsigned"), (8LU * (sizeof foo))); }
                   ^
     grovel-headers.c:403:5: error: expected expression
     grovel-headers.c:78:15: note: expanded from macro 'DEFTYPE'
                (((foo=-1)<0) ? "signed" : "unsigned"), (8LU * (sizeof foo))); }
                   ^
     grovel-headers.c:403:5: error: use of undeclared identifier 'foo'
     grovel-headers.c:78:67: note: expanded from macro 'DEFTYPE'
                (((foo=-1)<0) ? "signed" : "unsigned"), (8LU * (sizeof foo))); }
                                                                       ^
     grovel-headers.c:408:29: error: unknown type name 'os_vm_size_t'; did you mean 'vm_size_t'?
         DEFTYPE("os-vm-size-t", os_vm_size_t);
                                 ^~~~~~~~~~~~
                                 vm_size_t
     grovel-headers.c:76:35: note: expanded from macro 'DEFTYPE'
     #define DEFTYPE(lispname,cname) { cname foo; \
                                       ^
     /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/mach/arm/vm_types.h:105:33: note: 'vm_size_t' declared here
     typedef uintptr_t               vm_size_t;
                                     ^
     9 errors generated.
     make: *** [grovel-headers] Error 1