lang/wabt:  add WABT
NOT building with error

[…]
     [100%] Building CXX object CMakeFiles/wasm.dir/src/interp/interp-wasm-c-api.cc.o
     /usr/bin/clang++ -DWASM_API_EXTERN="__attribute__((visibility(\"default\")))" -D__STDC_FORMAT_MACROS=1 -D__STDC_LIMIT_MACROS=1 -Dwasm_EXPORTS -I/opt/local/var/macports/build/_Users_evenson_work_macports-ports_lang_wabt/wabt/work/1.0.36/third_party/wasm-c-api/include -I/opt/local/var/macports/build/_Users_evenson_work_macports-ports_lang_wabt/wabt/work/1.0.36/include -I/opt/local/var/macports/build/_Users_evenson_work_macports-ports_lang_wabt/wabt/work/build/include -isystem /opt/local/libexec/openssl3/include -pipe -Os -DNDEBUG -I/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -Wold-style-cast -fno-exceptions -std=c++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -mmacosx-version-min=14.0 -fPIC -fvisibility=hidden   -Wall -Wextra -Wno-unused-parameter -Wpointer-arith -Wuninitialized -Wimplicit-fallthrough -Wno-old-style-cast -MD -MT CMakeFiles/wasm.dir/src/interp/interp-wasm-c-api.cc.o -MF CMakeFiles/wasm.dir/src/interp/interp-wasm-c-api.cc.o.d -o CMakeFiles/wasm.dir/src/interp/interp-wasm-c-api.cc.o -c /opt/local/var/macports/build/_Users_evenson_work_macports-ports_lang_wabt/wabt/work/1.0.36/src/interp/interp-wasm-c-api.cc
     /opt/local/var/macports/build/_Users_evenson_work_macports-ports_lang_wabt/wabt/work/1.0.36/src/interp/interp-wasm-c-api.cc:17:10: fatal error: 'wasm.h' file not found
        17 | #include <wasm.h>
           |          ^~~~~~~~

[…]

Need to use git checkout to get third-party subdirectory properly?